name: Continuous Integration

# Diz ao GitHub para rodar esse processo toda vez que houver um Push ou Pull Request
on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  test:
    # Escolhe uma máquina com Ubuntu (Linux) atualizado para rodar o projeto
    runs-on: ubuntu-latest

    steps:
    # Passo 1: Copia o código do seu repositório para dentro da máquina virtual
    - name: Checkout code
      uses: actions/checkout@v4

    # Passo 2: Instala o Node.js na máquina virtual (versão 20 que é super estável)
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: 'npm'
        cache-dependency-path: 'Back-End/package-lock.json'

    # Passo 3: Instala todas as dependências do seu package.json
    - name: Install dependencies
      run: npm install

    # Passo 4: GERA OS TIPOS DO PRISMA (Isso é obrigatório para o Jest não dar erro de falta de tipos no CI!)
    - name: Generate Prisma Client
      run: npx prisma generate

    # Passo 5: Roda a sua suíte de testes do Jest
    - name: Run tests
      run: npm run test