name: Continuous Integration

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main", "master", "develop" ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./Back-End

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    # Removidas as linhas de cache, mantendo apenas a versão do Node
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    - name: Generate Prisma Client
      run: npx prisma generate

    - name: Run tests
      run: npm run test